# Generated by Django 4.1.3 on 2022-12-01 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=32, verbose_name='出版社名称')),
                ('publisher_address', models.CharField(max_length=32, verbose_name='出版社地址')),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inventory', models.IntegerField(verbose_name='库存数')),
                ('sale_num', models.IntegerField(verbose_name='卖出数')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.publisher')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('book', models.ManyToManyField(to='manager.book')),
            ],
            options={
                'db_table': 'author',
            },
        ),
    ]
