# Generated by Django 5.2 on 2025-05-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_book_cover_image_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='客户邮箱')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='客户电话')),
                ('shipping_address', models.TextField(verbose_name='收货地址')),
                ('shipping_city', models.CharField(max_length=50, verbose_name='城市')),
                ('shipping_state', models.CharField(blank=True, max_length=50, verbose_name='省份')),
                ('shipping_country', models.CharField(default='中国', max_length=50, verbose_name='国家')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=20, verbose_name='邮政编码')),
                ('payment_method', models.CharField(choices=[('credit_card', '信用卡'), ('debit_card', '借记卡'), ('paypal', 'PayPal'), ('alipay', '支付宝'), ('wechat_pay', '微信支付'), ('bank_transfer', '银行转账'), ('cash_on_delivery', '货到付款')], max_length=20, verbose_name='支付方式')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('confirmed', '已确认'), ('processing', '处理中'), ('shipped', '已发货'), ('delivered', '已送达'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='订单状态')),
                ('customer_notes', models.TextField(blank=True, verbose_name='客户备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.book', verbose_name='图书')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单项目',
                'verbose_name_plural': '订单项目',
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='会话密钥')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.book', verbose_name='图书')),
            ],
            options={
                'verbose_name': '购物车项目',
                'verbose_name_plural': '购物车项目',
                'db_table': 'cart_item',
                'unique_together': {('session_key', 'book')},
            },
        ),
    ]
