# Generated by Django 5.2 on 2025-10-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, help_text='上传图书PDF、EPUB等文件，或者留空使用下载链接', null=True, upload_to='book_files/', verbose_name='图书文件'),
        ),
        migrations.AddField(
            model_name='book',
            name='download_link',
            field=models.URLField(blank=True, help_text='外部下载链接（Google Drive、OneDrive等）', max_length=500, null=True, verbose_name='下载链接'),
        ),
    ]
